### PR TITLE
Rewrite for APIv3

### PR DESCRIPTION
**Pull request by ErikBoesen**
In this pull request, I've rewritten the entire library to be compatible with TBA API v3.

The new library is instantiated differently than the prior version. Furthermore, as specified in #4, the rewrite uses a builder pattern to construct requests before sending them to TBA's API. For example:

```go
tba.New("tokenhere") // Go best practices advocate using New for libraries with one exposed interface
team, err := tba.Team(1418).Simple().Get()
// ...
rankings, err := tba.District("chs", 2017).Rankings().Get()
// etc.
```

I've ignored concerns about backward compatibility based on the facts that (a) APIv2 will be shuttered on January 1st, 2018, and (b) I am the only current user of this library and am prepared to make changes to my projects.

I've aggressively tested my implementation and I can't find any issues with it. However, since you've been using Go longer than I have, you may see problems with standards conformity or the like. Please point these out if they at all exist and I'll happily fix them.

Lastly, I'd like to humbly request that you transfer this repository to my account. I recognize that you are in college now and are probably very busy; I don't want to waste your time by submitting pull request after pull request as I continue developing this library. Please let me know if this is something you'd be comfortable with.

### CODE REVIEW

**Comment by ErikBoesen** [comment]
Also, it's probably best to squash this into one commit when you merge.

**Comment by CarlColglazier** [comment]
This looks really great! I am pleased to see that the builder design patter could be put to good use here.

I would be happy to transfer the repository to you.

**Comment by CarlColglazier** [comment]
You will need to delete your fork before I can perform the transfer: https://help.github.com/articles/about-repository-transfers/

**Comment by ErikBoesen** [comment]
Done. Didn't want to delete until this was merged.

Thanks so much for your help!

**Pull request merged**
